### ISSUE TITLE
Graphite container broken due to upstream package removing Python 2.7 support

### ISSUE THREAD

**Issue by scaleoutsean** [jedimt/hcicollector#17]
Building from `master`:

```
Removing intermediate container 0460f6459635
 ---> d61d74d3872a
Step 4/16 : RUN   mkdir -p /opt &&   cd /opt &&   curl -sLo statsd.tar.gz https://github.com/etsy/statsd/archive/v0.8.0.tar.gz &&   tar -xzf statsd.tar.gz &&   mv statsd-0.8.0 statsd
 ---> Running in 3984a8755299
Removing intermediate container 3984a8755299
 ---> 9dd2b44bcfd9
Step 5/16 : RUN pip install graphite-api[sentry] whisper carbon
 ---> Running in 5accf0300cd1
Downloading/unpacking graphite-api[sentry]
Downloading/unpacking whisper
  Downloading whisper-1.1.5.tar.gz
  Running setup.py (path:/tmp/pip_build_root/whisper/setup.py) egg_info for package whisper
    
Downloading/unpacking carbon
  Running setup.py (path:/tmp/pip_build_root/carbon/setup.py) egg_info for package carbon
    ################################################################################
    
    Carbon's default installation prefix is "/opt/graphite".
    
    To install Carbon in the Python's default location run:
    $ GRAPHITE_NO_PREFIX=True python setup.py install
    
    ################################################################################
    
    package init file 'lib/twisted/plugins/__init__.py' not found (or not a regular file)
    warning: no files found matching '*' under directory 'conf/'
    warning: no files found matching '*' under directory 'distro/'
    warning: no previously-included files found matching 'conf/*.conf'
Downloading/unpacking cairocffi (from graphite-api[sentry])
  Running setup.py (path:/tmp/pip_build_root/cairocffi/setup.py) egg_info for package cairocffi
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/cairocffi/setup.py", line 7, in <module>
        'cairocffi does not support Python 2.x anymore. '
    RuntimeError: cairocffi does not support Python 2.x anymore. Please use Python 3 or install an older version of cairocffi.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/cairocffi/setup.py", line 7, in <module>

    'cairocffi does not support Python 2.x anymore. '

RuntimeError: cairocffi does not support Python 2.x anymore. Please use Python 3 or install an older version of cairocffi.
```
This is where it breaks: https://github.com/jedimt/hcicollector/blob/v6/graphite/Dockerfile#L17
cairocffi unsupported Python 2.6 and 2.7 few days ago (https://github.com/Kozea/cairocffi/commit/c93eb812ab54ab6666cbeb1c8eb64934c3cc4544) so now that container doesn't build. 

We could mess around with that image to fix it, or move to a newer image (which seems better because in coming months more Python 2.7 packages will go away).

**Comment by jedimt** [comment]
Merged in Sean's fixes
