### ISSUE TITLE
"NewBase must define encode" error in hcicollector_graphite

### ISSUE THREAD

**Issue by ybizeul** [jedimt/hcicollector#8]
Carbon doesn't start in the container with the following exception.

```
Traceback (most recent call last):
  File "/opt/graphite/bin/carbon-cache.py", line 32, in <module>
    run_twistd_plugin(__file__)
  File "/opt/graphite/lib/carbon/util.py", line 140, in run_twistd_plugin
    runApp(config)
  File "/usr/local/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 25, in runApp
    runner.run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 381, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 448, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
  File "/opt/graphite/lib/twisted/plugins/carbon_cache_plugin.py", line 20, in makeService
    from carbon import service
  File "/opt/graphite/lib/carbon/service.py", line 36, in <module>
    import carbon.amqp_listener
  File "/opt/graphite/lib/carbon/amqp_listener.py", line 46, in <module>
    from txamqp.protocol import AMQClient
  File "/usr/local/lib/python2.7/dist-packages/txamqp/protocol.py", line 15, in <module>
    from txamqp.connection import Header, Frame, Method, Body, Heartbeat
  File "/usr/local/lib/python2.7/dist-packages/txamqp/connection.py", line 60, in <module>
    class Payload(with_metaclass(PayloadMeta, object)):
  File "/usr/lib/python2.7/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "/usr/local/lib/python2.7/dist-packages/txamqp/connection.py", line 52, in __new__
    raise TypeError("%s must define %s" % (name, req))
TypeError: NewBase must define encode
```

**Comment by jedimt** [comment]
Have confirmed this is working in the v7 build now.
